[platformio]
boards_dir = boards

[env]
framework = arduino
upload_speed = 460800
lib_deps =
    Wire
    EEPROM
    olikraus/U8g2 @ ^2.33.15
monitor_speed = 74880
build_flags = 
  -D ENABLE_AUTO_SAVE_STATUS
  -D ENABLE_LOAD_STATE_FROM_EEPROM
  -D AUTO_SAVE_MINUTES=2
  ; -D ENABLE_DUMP_STATE_TO_SERIAL_WHEN_START
  ; -D ENABLE_SERIAL_DEBUG_INPUT
  ; -D ENABLE_LOAD_HARCODED_STATE_WHEN_START

[t-qt-pro]
platform = espressif32@6.12.0
board = esp32-s3-t-qt-pro
framework = arduino
lib_extra_dirs =
  C:/Users/manuc/Desktop/DESKTOP/T-QT-main/T-QT-main/lib
lib_deps =
build_flags =
  ${env.build_flags}
  -D SERIAL_BAUD=115200
  -D SCREEN_WIDTH=128
  -D SCREEN_HEIGHT=128
  -D T_QT_PRO
  -D PIN_BTN_L=0
  -D PIN_BTN_R=47
  -D CPU_SPEED_RATIO=1
  -D T_QT_DISPLAY_ROTATION=2
  -D TAMA_DISPLAY_FRAMERATE=8
  -D T_QT_WIFI_MONITOR
monitor_speed = 115200

; [env:nanoatmega328]
; platform = atmelavr
; board = nanoatmega328
; build_flags = 
;   ${env.build_flags}
;   -D TAMA_DISPLAY_FRAMERATE=3

[env:tamagotchi-kit-a]
platform = espressif8266
board = esp12e
build_flags = 
  ${env.build_flags}
  -D PIN_BTN_L=12
  -D PIN_BTN_M=13
  -D PIN_BTN_R=15
  -D PIN_BUZZER=2
  -D TAMA_DISPLAY_FRAMERATE=8

[env:tamagotchi-kit-b]
platform = espressif8266
board = esp12e
build_flags = 
  ${env.build_flags}
  -D PIN_BTN_L=12
  -D PIN_BTN_M=13
  -D PIN_BTN_R=15
  -D PIN_BUZZER=0
  -D ENABLE_TAMA_SOUND
  -D ENABLE_TAMA_SOUND_ACTIVE_LOW
  -D TAMA_DISPLAY_FRAMERATE=8

[env:tamagotchi-kit-c]
platform = espressif8266
board = esp12e
build_flags = 
  ${env.build_flags}
  -D PIN_BTN_L=12
  -D PIN_BTN_M=13
  -D PIN_BTN_R=15
  -D PIN_BUZZER=0
  -D ENABLE_TAMA_SOUND
  -D ENABLE_TAMA_SOUND_ACTIVE_LOW
  -D TAMA_DISPLAY_FRAMERATE=8
  
[env:tamagotchi-kit-d]
platform = espressif32
board = lolin_s2_mini
board_build.f_cpu = 80000000
build_flags = 
  ${env.build_flags}
  -D PIN_BTN_L=9
  -D PIN_BTN_M=11
  -D PIN_BTN_R=12
  -D PIN_BUZZER=18
  -D PIN_I2C_SDA=33
  -D PIN_I2C_SCL=35
  -D ENABLE_TAMA_SOUND
  -D ENABLE_TAMA_SOUND_ACTIVE_LOW
  -D TAMA_DISPLAY_FRAMERATE=16

[env:t-qt-pro-n4r2]
extends = t-qt-pro
build_flags =
  ${t-qt-pro.build_flags}
  -D BOARD_HAS_PSRAM

[env:t-qt-pro-n8]
extends = t-qt-pro
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv
